# Machine
machine: local
# arguments
sceneId: 246
dataMode: total3d
renderPartId: true
renderNormal: true
renderUV: true
renderDepth: true
initImgHeight: 480
initImgWidth: 640
isOverWriteSampledView: false
singleLightImgHeight: 240
singleLightImgWidth: 320
imgHeight: 240
imgWidth: 320
nSamplePerPixel: 2048
isOverWriteSelectedView: false

# graph selection parameters
usekNN: true
graphSelectBatchSize: 6
graphSelectToGray: false
kNum : 21
nSamplePerGraph: 10
nUvAngStep: 1
nUvScaleStep: 1

# optimization parameters
useHomoRough: true
optObjectives:
  - stat
  - vgg
optObjectivesCoeff:
  - 100
  - 1

# n or j
uvOptimMode: s
# useful when uvOptimMode is j
uvOptim:
  scale: true
  rotation: true
  translation: true
uvOptimLr:
  scale: 0.08
  rotation: 0.06
  translation: 0.01
uvSearchParam:
  scaleBase: 1.5
  # min included
  scaleExpMin: -3.5
  # max not included
  scaleExpMax: 4.5
  # number of steps between min and max
  scaleStepNum: 32
  # divide 2PI to $rotStep steps
  rotStepNum: 72
  # divide [-0.5, 0.5] into $transStepNum for both X and Y
  transStepNum: 5

useAlbOffset: true
matRes: 8
modeId: 1
seed: 0
# modeName: stat-100-vgg-1

# yaml
rootConfig: configs/roots.yaml