# Renderer
OptixRoot: third_party/OptiX
rendererRoot: third_party/OptiX_Renderer
# MaskFormer Dir
maskformerRoot: third_party/MaskFormer
# Inverse render net root
invrenderRoot: third_party/InverseRenderingOfIndoorScene
# Total 3D Dir
total3dRoot: third_party/Total3D
# data root
inputDir: data
outputDir: outputs
# graph sample dir
graphSampleDir: graphsSamples
